### ISSUE TITLE
FunctionClauseError in Utils.extract_opts/1

### ISSUE THREAD

**Issue by DianaOlympos** [nccgroup/sobelow#1]
**What did i do :** 
Inside an API only phoenix project inside an umbrella app, after calling `mix sobelow`, we got a couple of hits, then the following error.

```
** (FunctionClauseError) no function clause matching in Sobelow.Utils.extract_opts/1
    lib/sobelow/utils.ex:158: Sobelow.Utils.extract_opts({:pipe, {{:., [line: 25], [{:__aliases__, [line: 25], [:Plug, :Conn]}, :send_file]}, [line: 25], [200, {:filename, [line: 25], ["categories"]}]}})
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/sobelow/traversal/send_file.ex:65: Sobelow.Traversal.SendFile.parse_aliased_send_file_def/1
    lib/sobelow/traversal/send_file.ex:52: Sobelow.Traversal.SendFile.parse_send_file_def/1
    lib/sobelow/traversal/send_file.ex:12: Sobelow.Traversal.SendFile.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
```

It does not happen in a phoenix project with html stuff, for what it is worth, in the same umbrella.

I can sadly not disclose the code of the app in question.

Environnement :
macOS Sierra 10.12.4
elixir 1.4.2
erlang/OTP 19.3
Phoenix 1.2.1

**Comment by GriffinMB** [comment]
Thanks for the report, I just pushed a fix to the feature branch that should address the issue. Could you try installing with:

`mix archive.install https://github.com/nccgroup/sobelow/raw/feature/sobelow.ez`

And then re-run the test and let me know if there is still an issue.

**Comment by DianaOlympos** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by GriffinMB** [comment]
Great, pushed to master!
