### ISSUE TITLE
Create tags in github repository to match releases in hex

### ISSUE THREAD

**Issue by squaresurf** [nccgroup/sobelow#102]
This repository only has tags up to v0.10.0. What do you think about also adding the others up to the current release (i.e. v0.11.1)?

**Comment by OldhamMade** [comment]
Also, would it be possible to get a release pushed to hex.pm with my flycheck changes? They were merged ~6 months ago but they're still not available without a direct `head` install from gh.

**Comment by houllette** [comment]
Current released version on Hex is 0.11.1, I recently took on maintaining the project and will be looking to push a new version up soon that contains a few QOL improvements 🙂
