### ISSUE TITLE
multiple routers (not an umbrella :) )

### ISSUE THREAD

**Issue by danturn** [nccgroup/sobelow#109]
Heya, 

Just wondering if sobelow might support our current setup or not,

we have a `core router` that proxies requests onto multiple other more traditional routers...

```
    use Plug.Router, init_mode: Application.compile_env(:phoenix, :plug_init_mode, :compile)
    plug :match
    plug :dispatch

    match("/:role/login", to: CommonWeb.Router)
```

we do have a router at lib/platform_web/router.ex but it one of a few...

it looks like you expect a single router?

im wondering 

a) if my assumptions are right? and 
b) is there a way to make sure we're scanning all our routes?

i guess i can run multiple runs with a different --router param each time?

**Comment by houllette** [comment]
Hey @danturn! Sorry for the delay on this response - I looked into this and I _believe_ that Sobelow will support multiple routers automatically like you explained. 

Sobelow will initially look for the default router in the location that Phoenix initially establishes it, but Sobelow will still parse all files and conduct analysis to compile a list of all router files (seen [here](https://github.com/nccgroup/sobelow/blob/master/lib/sobelow.ex#L73)).
