### ISSUE TITLE
Traversal.FileModule Issue.

### ISSUE THREAD

**Issue by apoorv-2204** [nccgroup/sobelow#114]
```
defp recover_path(), do: Utils.mut_dir("slot_backup")

  defp backup_slot(slot) do
    content = serialize(slot)

    recover_path()
    |> File.write!(content, [:append, :binary])
  end

   content = File.read!(recover_path())
```

Path to file is being collected from a function call, which appends the path around, sobelow , still reports it as as Issue.
For FileRead , write.

**Comment by houllette** [comment]
Closing this issue in favor of older, similar issue. Have noted this particular case in that issue to keep track of it and make sure this still keeps addressed 🙂
