### ISSUE TITLE
Please match hex version code with github?

### ISSUE THREAD

**Issue by pdgonzalez872** [nccgroup/sobelow#116]
Hi @houllette and @GriffinMB ! Thanks for all your work!

I saw https://github.com/nccgroup/sobelow/issues/113#issuecomment-1372923859 and have a request: Could you please update github with the latest code from hex? Seems like a couple of versions were deployed directly to hex.

Thanks so much, this is awesome news!

**Comment by houllette** [comment]
Yup! We are still hashing out the details of setting up the Hex deploy secret, but once that's done and we get maybe one or two other small fixes in - you can be sure we'll push out a new version to Hex!
