### ISSUE TITLE
Consider replacing `@sobelow_skip` because of Elixir 1.4 compiler warnings

### ISSUE THREAD

**Issue by lleger** [nccgroup/sobelow#12]
We use Elixir’s `--warnings-as-errors` option on CI, which helps us ship tip-top code. However, in Elixir 1.4, using `@sobelow_skip` to turn off a Sobelow false-positive check will result in a compiler error. This means our CI runs fail to build. Here’s the error:

```bash
$ mix compile --warnings-as-errors
warning: module attribute @sobelow_skip was set but never used
Compilation failed due to warnings while using the --warnings-as-errors option
```

One way to get around this is to do `_ = @sobelow_skip` immediately below the usage, but that is an ugly hack.

```elixir
@sobelow_skip ["DOS.StringToAtom"]
def vulnerable(foo) do   
  _ = @sobelow_skip
  String.to_atom(foo)
end
```

I would recommend moving away from `@sobelow_skip` and consider something else — perhaps a code comment would work?

For reference, Credo also considered this same issue and decided to drop their own module attribute usage for a code comment: https://github.com/rrrene/credo/issues/291

**Comment by GriffinMB** [comment]
I'm going to think about it a little longer before making the change, but as of now I agree that code comments make the most sense. The new syntax would be a simple update, which is nice:

```elixir
# sobelow_skip ["DOS.StringToAtom"]
def vulnerable(foo) do
  String.to_atom(foo)
end
```
Thanks again for the report!

**Comment by GriffinMB** [comment]
@lleger The latest updates support the new comment syntax. I appreciate the report, and I hope this makes Sobelow easier to use. 

The old `@sobelow_skip` syntax will continue to work as well, so the transition should be fairly painless.

**Comment by lleger** [comment]
Works great, thanks!
