### ISSUE TITLE
Suggestion for installation instructions

### ISSUE THREAD

**Issue by dmarcoux** [nccgroup/sobelow#120]
`sobelow` is often running in continuous integration pipelines and when it does, it will more often than not be in the test environment. On top of this, `sobelow` doesn't have to be started as a [runtime application](https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-dependency-definition-options), so `runtime: false` should also be added to the installation instructions. This is what I suggest for the README:

```
def deps do
  [
    {:sobelow, "~> 0.11", only: [:dev, :test], runtime: false}
  ]
end
```

I am happy to send a PR if you agree with the suggestion.

**Comment by houllette** [comment]
Great suggestion, @dmarcoux - I would happily welcome a PR if you made one!
