### ISSUE TITLE
Support for non-phoenix projects?

### ISSUE THREAD

**Issue by mmmries** [nccgroup/sobelow#17]
I have a project that receives protobuf-encoded messages from a message broker. Would it be possible to add support for this type of system by noting where data is coming in from an outside system?

I would be happy to help out with this if there is an interest in supporting non-phoenix projects written in Elixir.

**Comment by GriffinMB** [comment]
Sobelow doesn't "officially" support scanning non-Phoenix applications, but in general it should work for any standard Elixir app. I've used it to scan parts of Elixir, Hex, and some other popular libraries. The Phoenix-specific support really just helps with the confidence levels, and in finding certain classes of vulnerabilities such as missing CSRF protection.  

Try scanning your project, and let me know how it works out. You can typically expect to get a lot of low-confidence findings from this kind of scan, but I've still found it helpful in pointing me towards vulnerabilities. 

Ultimately, I'd like to keep Sobelow Phoenix-focused, but it should still be useful outside of a Phoenix context. If you run into any errors scanning non-Phoenix applications, you should definitely open an issue!

**Comment by mmmries** [comment]
@GriffinMB thanks for the fast response :+1:

I tested it out with my non-phoenix app and it looks like it reports a few things. For instance I added a few lines to my project like:

```elixir
    System.cmd(shard_request.guid, ["wat"])
    fields = Enum.map(shard_request.options.select, &String.to_atom/1)
    String.to_atom(shard_request.guid)
```

It then reported the command injection error and the `String.to_atom` issue for the last line. Interestingly it didn't catch the issue with calling `String.to_atom` in the `Enum.map`, but that's probably just an enhancement for that particular check.

It also prints two error messages as the beginning of the scan:

```
ERROR: Sobelow cannot find the router. Ensure that this is a Phoenix
application, or use the `--router` flag to specify the router's
location.

ERROR: Could not read /web
```

So maybe I could add a command-line flag that tells sobelow not to expect phoenix things to be present? That way the user doesn't see it as an error?

**Comment by GriffinMB** [comment]
Glad it's flagging some stuff! And, yeah, the missed `&String.to_atom/1` is something that still needs to be addressed. There are a few cases throughout that need enhancement. 

As far as adding a command-line flag: I'm not sure. I like that the errors indicate that a user is getting into unknown territory, and things are going to be less precise. I don't want to lose that. So if a flag is added, I would want it to reflect that. Any ideas or thoughts on this?

**Comment by mmmries** [comment]
@GriffinMB I was thinking of a command-line flag like `--without-phoenix` that way it is still explicit to the user that they are disabling some features. This way the default behavior is still to expect a phoenix application, but for users who are intentionally scanning a non-phoenix project they can avoid error messages that don't apply to them.

But maybe it would be a better use time to just start working on enhancements to the current checks or additional ways to mark points of user-input in non-phoenix projects?

I'm happy to jump in and submit PRs, just want to make sure I'm submitting something useful.

BTW thank you for this awesome project. it's really helpful at my job to be able to use these types of automated checks. It makes it possible for us to use elixir without having to change any of our compliance checks. 💙 💛 💚 ❤️ 💙 💛 💚 ❤️ 💙 💛 💚 ❤️ 💙 💛 💚 ❤️ 💙 💛 💚 ❤️

**Comment by GriffinMB** [comment]
@mmries The `--without-phoenix` flag does seem like the best option, though I'm still not sure we should go that route. I'm going to close this for now.

Also, I have an update on master that should address your `&String.to_atom/1` issue! You can install it with `mix archive.install github nccgroup/sobelow`. This patch will likely be going live as 0.4.1 tomorrow, so you can also wait and install it the usual way if you'd prefer.

I'm glad you're finding Sobelow useful, and thank you for opening the issue!
