### ISSUE TITLE
New Phoenix 1.3 directory structure support

### ISSUE THREAD

**Issue by tmepple** [nccgroup/sobelow#18]
Hi @GriffinMB,

I was in the process of refactoring my Phoenix 1.3-rc app with the latest directory structure changes recently pushed to master https://github.com/phoenixframework/phoenix/commit/20e2826587b25227e107a83fbb56ce7f4d0c731f which currently breaks sobelow.  

When running `mix sobelow` I initially get the message that the router can't be found.  When passing the new location of the router `lib/my_app_web/router.ex` I then get an error message "Could not read /web".

I know you may not want to address this yet until at least another RC is released on Phoenix in case the directory structure is modified again in future commits but just wanted to let you know.  

Thanks for the great project!!

**Comment by GriffinMB** [comment]
Hey, thanks for opening the issue! I went ahead and pushed a fix to master. You can install with `mix archive.install github nccgroup/sobelow` for now, and I will push the fix to Hex in the next day or so. 

It's a fairly small fix, and I already supported the previous release candidate, so I imagine people will expect this to work as well. I'll just need to do some cleanup once the final release is out.

**Comment by tmepple** [comment]
Works great, thanks for getting it out so fast!  Also the new release candidate 3 of Phoenix was just released... looks likely now the newly tweaked directory structure will make it to final.
