### ISSUE TITLE
`--exit` doesn't change anything

### ISSUE THREAD

**Issue by NobbZ** [nccgroup/sobelow#19]
I do currently have no HTTPS configured and `mix sobelow` as well as `mix sobelow --exit` do exit with an exit code of 0.

This stops me using sobelow on CI.

**Comment by NobbZ** [comment]
Okay, after taking another look at the README, I found out that `--exit` takes an argument, sobelow should definitively fail if it is missing or not one of the 3 severity levels and give a proper explanation of how to use it.

**Comment by GriffinMB** [comment]
Hey! Thanks for opening this issue. I just updated Sobelow, and it now defaults to a "Low" threshold if no argument is provided with the `--exit` flag. Running `mix sobelow --exit` should now work as one would expect.
