### ISSUE TITLE
Other SQL injection vectors

### ISSUE THREAD

**Issue by michalmuskala** [nccgroup/sobelow#2]
Right now the only considered vector for SQL injections is `Ecto.Adapters.SQL.query/3`. Here are some more:

* since ecto 2.1 each repo defines `Repo.query/2` that delegates to the `Ecto.Adapters.SQL.query/3` function
* since ecto 2.1 there's `Ecto.Adapters.SQL.stream/4` for building a cursor streams based on a raw queries.

For analysis of repos, you can get a list of all repos using code below, since ecto requires defining the `ecto_repos` setting in order to have migrations, etc working properly.
```elixir
Application.loaded_applications()
|> Enum.flat_map(fn {app, _, _} -> Application.get_env(app, :ecto_repos, []) end) 
|> Enum.uniq
```

**Comment by GriffinMB** [comment]
This is great, thank you!

One potential issue for `Repo.query` is that sobelow won't necessarily (or even typically) have access to the scanned Application environment. Tangentially, I think this was actually also the issue I was having with Macro expansion. I can definitely work around the problem, or perhaps reconsider the separate application environments, but it'll take a bit of thought.

**Comment by michalmuskala** [comment]
If it's being executed through a mix task in the context of the application, it should have access to the application env.

**Comment by GriffinMB** [comment]
I was under the impression that, since it is installed globally rather than as a dependency, it wasn't actually run in the context of the application. Which is why deps don't need to be installed, etc

If that's not the case, that certainly makes life easier :)

**Comment by michalmuskala** [comment]
I'm pretty sure (though, not 100% sure) that if a task is invoked inside a mix project directory, it will load the env.

**Comment by GriffinMB** [comment]
A check for `stream` is now included. Still weighing my options for `Repo.query`, but that should be added soon as well. Thanks again for the report!

**Comment by michalmuskala** [comment]
Thank you! ❤️
