### ISSUE TITLE
Add `--compact` and `--quiet` options for less output

### ISSUE THREAD

**Issue by OldhamMade** [nccgroup/sobelow#22]
`sobelow` is very handy to be used with a git pre-commit hook, however the output is quite "long". It would be great if there were a `--quiet` option to only show output when there's a "failure", and a `--compact` option to reduce the vertical line impact on the console.

**Comment by GriffinMB** [comment]
Thanks for opening this issue! For `quiet`, do you mean just removing the banner and "... SCAN COMPLETE ..." message? If not, could you explain what you mean in a little more detail, or mockup some example output?

A `compact` option would be nice. The output will probably always be a little "long," but I can definitely work on trimming down some of the vertical "white space".

**Comment by OldhamMade** [comment]
For `quiet`, you should only see messages if there are errors.

For `compact`, one line per message. No banners, no frames, no blank lines.

For example, `quiet`:
```
Sobelow: checks failed. Run again without --quiet to review messages.
```

For `compact`:
```
[↑] Hardcoded Secret - apps/restricted/config/prod.secret.exs:11
[↑] HTTPS Not Enabled
[-] Unsafe `String.to_atom` - apps/restricted/lib/restricted/web/controllers/discount_controller.ex:47
```

**Comment by GriffinMB** [comment]
Great, thank you. I'll add both of these.

**Comment by GriffinMB** [comment]
The `--quiet` flag was added to 0.4.8. It is currently undocumented, but feel free to test it out! I'll be pushing the `--compact` flag in the next update, which should be done in the next couple of days. That update will also document the new features.

**Comment by GriffinMB** [comment]
Both flags added as of 0.4.9, thanks again for opening the issue.
