### ISSUE TITLE
-i not working.

### ISSUE THREAD

**Issue by davich** [nccgroup/sobelow#23]
Hi, I'm trying to run sobelow with the "-i" flag (following the example in the https.ex source file) and I'm getting an argument error.

> $ mix sobelow -i Config.HTTPS
> ** (ArgumentError) argument error
>    :erlang.binary_to_existing_atom("Elixir.Sobelow.Config.HTTPS", :utf8)
>    lib/sobelow.ex:351: Sobelow.get_mod/1
>    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
>    lib/sobelow.ex:47: Sobelow.run/0
>    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
>    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

Am I doing something wrong, or is this a bug? Thanks.

**Comment by GriffinMB** [comment]
Give it a shot now! Thanks for raising the issue
