### ISSUE TITLE
Can we have a CHANGELOG.md

### ISSUE THREAD

**Issue by davich** [nccgroup/sobelow#25]
Can we have a CHANGELOG.md to keep track of what has changed in each release version?

I want to upgrade for 0.5.1 to 0.6.2, but I don't know if there are breaking changes or extra features, etc.

**Comment by GriffinMB** [comment]
Yep, I can start including a CHANGELOG.md. 

In regards to the 0.5.1 to 0.6.2 upgrade, there shouldn't be any breaking changes. Improvements include additional checks for known-vulnerable dependencies, XSS, and DOS via dynamic atom creation, as well as some improvements and additional options for output formatting.

If you do upgrade and run into any issues, let me know! And you can always revert with `mix archive.install hex sobelow 0.5.1`.

**Comment by davich** [comment]
Thank you for your fast reply!

**Comment by GriffinMB** [comment]
A changelog has been added for the latest release. Thank you for opening the issue!
