### ISSUE TITLE
Timeout in version check

### ISSUE THREAD

**Issue by kyleaa** [nccgroup/sobelow#26]
It looks like there's currently an outage on for griffinbyatt.com - it takes a full minute for Cloudflare to return a 504 Gateway Timeout on this request. The terminal appears to just hang completely, as this check is performed before anything is written to out to the user. Could Sobelow print some sort of message before the network call to fetch the version so it's clear where it is hanging?

Also it appears that the `.sobelow` file is updated even if the check fails, I'm not sure if this is intended behavior or not.

**Comment by GriffinMB** [comment]
Thanks for opening this issue! I've updated Sobelow to print a message when it is attempting a version check, and added a 10 second timeout. 

I wanted the `.sobelow` file to be updated even on check failure to prevent a situation where a prolonged outage results in repeated, overlong request times. This may change in the future, but I think it works for now.
