### ISSUE TITLE
[Bug] 'String.Chars not implemented' for json format

### ISSUE THREAD

**Issue by uberspot** [nccgroup/sobelow#28]
Hi, I try sobelow in a private repo and I get:

        mix sobelow -v --router --format json
        ##############################################
        #                                            #
        #          Running Sobelow - v0.6.6          #
        #  Created by Griffin Byatt - @griffinbyatt  #
        #     NCC Group - https://nccgroup.trust     #
        #                                            #
        ##############################################

        ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:unquote, [line: 16], [:response_template]}
            (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
            (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
            lib/sobelow/utils.ex:173: Sobelow.Utils.log_json_finding/6
            (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:737: Enum.each/2
            (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:737: Enum.each/2
            (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2

Is this some library version mismatch?

        mix --version
        Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

        Mix 1.6.0 (compiled with OTP 19)

It happens in alpine, ubuntu and osx.

**Comment by GriffinMB** [comment]
Hey! Sorry you're running into an error. If you could answer a few questions, it shouldn't take long to track down this bug..

1. It looks like there is a bit of code that looks like `unquote(:response_template)` on line 16 in some file. Could you show me what the surrounding code looks like?
2. Was this happening in version 0.6.5? You can re-install the previous version with `mix archive.install hex sobelow 0.6.5`

Thanks!

**Comment by GriffinMB** [comment]
@uberspot - I pushed an update to master that should address this issue. You can download it with `mix archive.install github nccgroup/sobelow`. Let me know if it works out for you and I will add tests and push the update to hex later today.

Thanks for reporting!

**Comment by uberspot** [comment]
Yeap, tested it and it's fixed! 👍 
Thank you. :)

**Comment by uberspot** [comment]
This is unrelated but can you also make it not print 

    ##############################################
    #                                            #
    #          Running Sobelow - v0.6.6          #
    #  Created by Griffin Byatt - @griffinbyatt  #
    #     NCC Group - https://nccgroup.trust     #
    #                                            #
    ##############################################

this when --format json is used? It makes automating the tool usage more cumbersome. :)

**Comment by GriffinMB** [comment]
@uberspot Yep, I'll add that to 0.6.7 as well :)
