### ISSUE TITLE
Not well configured for umbrella projects

### ISSUE THREAD

**Issue by shouston3** [nccgroup/sobelow#30]
As a developer with a phoenix umbrella application. (`mix phx.new example --umbrella`).

I would like to use sobelow to test the main web (`apps/example_web`) directory successfully. (Perhaps an `--umbrella` flag would be a good thing to have to specify in this scenario).

Current usage:
```bash
mix sobelow -r apps/example_web --exit # produces: "cannot find router" warning and "could not read web directory" warning
mix sobelow -r apps/example --exit # produces: "cannot find router" warning and "could not read web directory" warning
```

I have had better results with
```bash
mix sobelow -r apps/example_web --router apps/example_web/lib/example_web/router.ex
```
but I still get the could not read `web` directory and can't specify the `web` directory.

The `web` directory is hardcoded here: https://github.com/nccgroup/sobelow/blob/master/lib/sobelow.ex#L229
When specifying `apps/example_web` as the `--root`, `app_name` is `"example_web"` and so `"#{app_name}_web"` will be `"example_web_web"` which is wrong.
(The code from lines 240-242 here will also not be correct here).

Would you accept a pr adding the use of an `--umbrella` flag which would have usage something like the following:

```bash
mix sobelow --umbrella
```

The command would go through each directory in `apps` and check if it is a phoenix application.
For each of those phoenix applications, we would run `mix sobelow`, and it would be nice to print out one single report.
It would also facilitate phoenix apps being called `example_web`.

**Comment by GriffinMB** [comment]
Hi! Thanks for creating the issue, and for your interest in helping with a PR. 

Your application should be appropriately scanned regardless of whether or not Sobelow can find the web directory. The warning is largely there to flag that something might be amiss with the directory structure. This can be verified by temporarily adding an insecure `String.to_atom` to a controller function in the web directory, and rescanning. If this is not the case, let me know (and send me a link to the app if it is open source)! 

I do think that the warning is giving the wrong impression of what has been scanned. I will add some language noting that this is an informational warning and that the lib directory has still been scanned.

As for the `--umbrella` flag, I think something like that is a good idea. Hold off on a PR for the moment though, I would like to think through it a bit more.

**Comment by GriffinMB** [comment]
@shouston3 - I've pushed an update to master; you can install it with `mix archive.install github nccgroup/sobelow`. This update clarifies the warning message you receive when scanning umbrella and non-standard applications (or if you are scanning libraries). 

```
WARNING: Web directory was not found in the expected location.
This may be a result of non-standard directory structure, or use
of an umbrella project. All files in the "lib" directory were
scanned for vulnerabilities.
```

Changes to the way routers are located means you should no longer need the `--router` flag in most instances, including in umbrella applications generated with `mix phx.new example --umbrella`. 

Let me know how these updates work for you! I will likely wait to push these changes to hex.pm until Sunday.

**Comment by shouston3** [comment]
Works exactly as described above, thank you for the lightning fast response @GriffinMB 🎉 

I am trialing out the changes to the sobelow master branch in my project.

Just so you know my use case (maybe the context would be helpful). For an umbrella project I am currently running sobelow checks in my ci in the following way:

```
  - mix sobelow --root apps/main_web --exit Low
  - mix sobelow --root apps/fx --root apps/fx --ignore-files config/prod.exs --exit Low
  - mix sobelow --root apps/ratewatch --root apps/ratewatch --ignore-files config/prod.exs --exit Low
```

**Comment by GriffinMB** [comment]
Awesome, glad it's working better for you now! 

And thank you for the examples, they are definitely helpful. I'll continue thinking about solutions for umbrella projects. It's something I would like to improve soon -- probably not in this Sunday's release, but hopefully in the next.

In the mean time you might find the `--config` option helpful. 

```
$ mix sobelow -r apps/ratewatch --ignore-files config/prod.exs --exit Low --save-config
$ mix sobelow -r apps/ratewatch --config
```

Still not the best for umbrella applications (and not as useful when running checks in a CI), but maybe it will save some keystrokes! :)

**Comment by GriffinMB** [comment]
I pushed the updates to Hex today. I'm going to go ahead and close this issue, because I think we covered the core problems you were having. I opened a new [issue](https://github.com/nccgroup/sobelow/issues/31) to track progress on scanning multiple applications.

Thanks again for opening this issue!
