### ISSUE TITLE
Add suggestions for fixes

### ISSUE THREAD

**Issue by seanhandley** [nccgroup/sobelow#32]
Awesome tool @GriffinMB 🙌 

What do you think about adding suggestions for how to fix the vulnerabilities flagged i.e.

> Use `String.to_existing_atom/1` instead of `String.to_atom/1` etc ?

I'm happy to raise a PR if you think this is something worth adding.

**Comment by GriffinMB** [comment]
Hey, thank you! Glad you're finding it useful.

Where it fits, I actually already have this functionality built in with the `-d` flag. For example:

```
$ mix sobelow -d DOS.StringToAtom
# Denial of Service via `String.to_atom`

In Elixir, atoms are not garbage collected. As such, if user input is passed to
the String.to_atom function, it may result in memory exhaustion. Prefer the
String.to_existing_atom function for untrusted user input.

String.to_atom checks can be ignored with the following command:

    $ mix sobelow -i DOS.StringToAtom
```

This isn't as discoverable as I would like -- in particular, finding the appropriate module name is less-than-ideal. I'm considering adding the module name to the output to make that easier. So it would look more like this:

```
$ mix sobelow
DOS.StringToAtom: Unsafe `String.to_atom` - High Confidence
File: target/web/controllers/page_controller.ex - show:20
Variable: page

-----------------------------------------------
```

Thoughts?

**Comment by seanhandley** [comment]
That's a step in the right direction for sure 👍 

I'm thinking more like a `--suggestions` flag that prints out a suggestion of how to mitigate the vulnerability (or how to understand the root cause in depth, at least).

**Comment by GriffinMB** [comment]
Got it, that sounds like a good addition.

I'll add both changes (the new flag, and the module name in the title) to the next release. It will likely coincide with some restructuring changes I've been working on, so no need for a PR. But thank you for the offer and for opening the issue :)

**Comment by seanhandley** [comment]
Awesome! 🙌

**Comment by GriffinMB** [comment]
There is an update on master that contains the module name in the finding details, which should greatly improve discoverability. Now you can do something like this:

```
$ mix sobelow --compact
[+] Config.CSP: Missing Content-Security-Policy

$ mix sobelow -d Config.CSP
# Missing Content-Security-Policy

Content-Security-Policy is an HTTP header that helps mitigate a number of
attacks, including Cross-Site Scripting.

Read more about CSP here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Missing Content-Security-Policy is flagged by sobelow when a pipeline
implements the :put_secure_browser_headers plug, but does not provide a
Content-Security-Policy header in the custom headers map.

Documentation on the put_secure_browser_headers plug function can be found
here:
https://hexdocs.pm/phoenix/Phoenix.Controller.html#put_secure_browser_headers/2

Content-Security-Policy checks can be ignored with the following command:

    $ mix sobelow -i Config.CSP

```

An `--include-details` flag didn't end up working for a couple of reasons. The major one being that the details are fairly long, and there isn't always clear-cut advice. Dumping all of it with each finding ended up being a lot of noise. Hopefully the newly discoverable module names make this easier to get more information though :). And there is always `--all-details` for anyone craving an info dump!

Thanks again for opening this issue. Surfacing module names was a much-needed improvement. Sorry the ultimate fix took such a long time!
