### ISSUE TITLE
Feature request: Output captured in file

### ISSUE THREAD

**Issue by vraravam** [nccgroup/sobelow#39]
Currently, the output is printed to `stdout`, but as part of our CI jobs, it would be easier to capture this as a file to be saved as a build artifact. Could you please provide this?

**Comment by optikfluffel** [comment]
@vraravam wouldn't something like `mix sobelow --format json > sobelow_output.json` work for now?

**Comment by vraravam** [comment]
@optikfluffel - redirecting stdout/stderr output is not without downsides. In some cases it would mask the exit code. Also, different SAAS CI tools behave differently. The most consistent way (imo) to get this done would be for the tool to support an output file. Whether the format is JSON, text, or anything else can still be governed by the existing functionality.

Also, FYI, when we redirect output, it captures *all* output, so, for a codebase where the `_build` folder is not present, it would capture tens of lines related to compiling each individual dependency.

**Comment by vraravam** [comment]
@optikfluffel - yes, that is similar to what i was hoping to get implemented.

**Comment by GriffinMB** [comment]
Hi, thanks for opening an issue!

I just pushed a new release. You can now run `mix sobelow --out <filename>.json` to get JSON output written to a file. Running without a ".json" extension will default to the "quiet" format, so you'll get something like "Sobelow: XX findings found. Run again without --quiet to review findings" written to the output file.

Those are the only two formats supported for now, since the others are currently intended to be streamed/viewed from the terminal.

**Comment by vraravam** [comment]
@GriffinMB - thanks for the very quick turnaround on the feature request. Kudos to you for this and, in general, for this package.
I'm reopening this issue to be able to do 2 things:
1) Not restrict the filename extension; and 
2) Being able to save this new config in the configuration file for later runs of the tool.

**Comment by GriffinMB** [comment]
@vraravam:

> thanks for the very quick turnaround on the feature request. Kudos to you for this and, in general, for this package

Thank you, and no problem :)

Are you okay being restricted to the JSON and "quiet" output formats for the time being? If so, those changes should be very simple, and I could push a new release in the next day or so. Support for additional formats (such as txt) would come later - likely in the next few weeks, as I'm a bit busy with the holidays.

**Comment by vraravam** [comment]
@GriffinMB 
> Are you okay being restricted to the JSON and "quiet" output formats for the time being?
Yes - for the time-being, I'm ok with the JSON output alone.

But, the file-name-extension is a no-go for me. Also, saving this option into the config file is something that I need immediately as well.
Sorry to trouble you during the holidays. Happy Thanksgiving!

**Comment by GriffinMB** [comment]
Updated! `--save-config` works as intended, and you can use any extension you'd like. 

Thanks again for opening the issue. Happy holidays :)
