### ISSUE TITLE
Incorrect Status - Hardcoded Secret - High Confidence

### ISSUE THREAD

**Issue by samhamilton** [nccgroup/sobelow#4]
Hello, 

I just wanted to report that the tool reports the following as 

```
Hardcoded Secret - High Confidence
File: /config/prod.exs - line 31
Type: password
```

The corresponding line 31 is the first 
```
config :martide, Martide.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${DB_USER}",
  password: "${DB_PASSWORD}",
  database: "${DB_NAME}",
  hostname: "${DB_HOST}",
  pool_size: 20,
  loggers: [
    {Ecto.LogEntry, :log, []},
    {ScoutApm.Instruments.EctoLogger, :log, []}
  ]
```

We use edeliver and locally set environment variables on the server to replace `${DB_USER}` with actual values on deploy. 

Thanks
Sam

**Comment by GriffinMB** [comment]
Hey Sam, thanks for the report! 

This should be a fairly straightforward fix, I'll include it in the next minor release.

**Comment by GriffinMB** [comment]
The new version should work properly now, and comes along with some bug fixes :)
