### ISSUE TITLE
Usage with umbrella projects

### ISSUE THREAD

**Issue by brandonparsons** [nccgroup/sobelow#5]
I'm trying to run `mix sobelow` in my Elixir/Phoenix umbrella project, and I keep getting `This does not appear to be a Phoenix application`.

Any way to make this work?

**Comment by GriffinMB** [comment]
Hey Brandon,

You'll want to target the Phoenix app(s) specifically. For example:

`$ mix sobelow -r apps/app_web`

**Comment by brandonparsons** [comment]
Hmmm - this doesn't seem to work for me either. I created the Phoenix app with the version `1.3` installer. Are there differences there that could be messing it up?

**Comment by GriffinMB** [comment]
Is the app open source, or are you able to recreate the steps that result in this issue? It would be useful to have access so I can properly debug this.

Sobelow makes a couple of assumptions about Phoenix projects, that should hold true if they're generated with `mix phx.new`. It will return the error you are receiving if it can't find the app name, which it expects to find under the "app" option of the `project` function, and if it can't find the router, which (in a phoenix 1.3 app) it expects to find at `lib/app_name/web/router.ex`. 

For example, [firestorm](https://github.com/dailydrip/firestorm) is an umbrella app with a web application that adheres to the standard phoenix structure. From the project root, it would be scanned with `$ mix sobelow -r apps/firestorm_web`.

Let me know if you're still having trouble, or which assumption Sobelow makes that isn't true for your app. 

I'll also add some detail to error messages so it's more clear in the future!

**Comment by brandonparsons** [comment]
Hi @GriffinMB - thanks for the quick reply. I do this in my spare time so I'm a bit slower :)

App is not open source, but I expect the issue is where sobelow is looking for the router. I have my router split into separate modules, as the elixir app is serving two subdomains that need access to the same app code.

My router would be at something like `lib/myapp/frontend/a_module/router.ex`.

Would it be possible to make the router location configurable?

And yeah - would probably be a good idea to say "can't find router!" or similar on that failure message :)

**Comment by GriffinMB** [comment]
Hey, not a problem! Thanks for all the info, the router definitely seems to be the problem.

I'll try to implement some kind of fix for this sometime this week. A `--router` flag could work, and would be simple enough.

**Comment by GriffinMB** [comment]
Hey @brandonparsons, just pushed 0.3.1 which should address your issue!

Sobelow will no longer hard-error when it cannot find the router, and will encourage the use of the new `--router` flag. With your setup, the command could look a bit like this:

```
$ mix sobelow -r apps/app_web --router ../frontend/a_module/router.ex
```

**Comment by brandonparsons** [comment]
Great! I think this got me most of the way there. I have moved around a few of my other files though to accommodate the two parts of the app. Now when I run sobelow:

```
$ mix sobelow --root ./apps/frontend --router ./apps/frontend/lib/frontend/myapp/router.ex
ERROR: Could not read /apps/frontend/web

##############################################
#                                            #
#          Running Sobelow - v0.3.1          #
#  Created by Griffin Byatt - @griffinbyatt  #
#     NCC Group - https://nccgroup.trust     #
#                                            #
##############################################

HTTPS Not Enabled - High Confidence

-----------------------------------------------

... SCAN COMPLETE ...
```

It looks like it's assuming I have a web folder. What file exactly is sobelow looking for here? I've structured my application more like a standard elixir app (using umbrellas), so don't have a web folder.

**Comment by GriffinMB** [comment]
Sobelow expects a Phoenix project to have a "web" directory, but should be scanning everything regardless. The error message is there more as a sanity check to warn people if they are accidentally scanning the wrong application. 

With the web check and router check no longer hard-failing, Sobelow will pretty much attempt to scan anything you say is a Phoenix project!

**Comment by brandonparsons** [comment]
@GriffinMB Cool - thanks. I was just assuming I'd have run into more errors as this is my first shot at a Phoenix application :)

Thank you for working on this package. I think it will be an important part of the Phoenix ecosystem.
