### ISSUE TITLE
sobelow version check

### ISSUE THREAD

**Issue by InoMurko** [nccgroup/sobelow#51]
Hi,

if you install sobelow dynamically via `mix` I presume the tool does not create a `.sobelow` file. Which errors the version check:
https://app.circleci.com/jobs/github/omisego/elixir-omg/21795

**Comment by GriffinMB** [comment]
Unfortunately that's a bug in the recursive umbrella scan. I've reverted that change and published version 0.9.1. With this latest update, the error should go away. Thank you for reporting this issue!
