### ISSUE TITLE
Possibility to handle multiple routers

### ISSUE THREAD

**Issue by TBK145** [nccgroup/sobelow#52]
Hi,

We're starting to use this project, but ran into an issue using the `--router` flag. Our project is an umbrella, and we have multiple routers for different subapplications. I was wondering if you could add a possibility to add multiple routers, for instance by expanding a path or allowing for multiple instances of the flag. Or if you would be open to a pull request solving this.

Thanks!

**Comment by GriffinMB** [comment]
Hey! Thanks for opening an issue.

Currently, for umbrella applications, you should run sobelow separately in each subapplication. Typically, people will create a simple shell script to run each scan.

Hope this helps!
