### ISSUE TITLE
Sobelow.XSS.Raw JSON schema missing `line` key

### ISSUE THREAD

**Issue by NickMeves** [nccgroup/sobelow#54]
Hey there,

The mandatory `line` key appears to be missing from here:
https://github.com/nccgroup/sobelow/blob/6b8a89282acde1931945a31f2f93741651e410e4/lib/sobelow/xss/raw.ex#L113

```
case Sobelow.format() do
      "json" ->
        json_finding = [
          type: finding.type,
          file: finding.filename,
          variable: "#{finding.vuln_variable}",
          template: "#{t_name}"
        ]
```

I haven't tested this live (in case it is handled elsewhere).  I just noticed when I was trying to get a feel for the optional JSON keys various types might present back.

Thanks!

**Comment by GriffinMB** [comment]
Thanks for opening the issue! You're right, "line" is missing from the JSON output. I just pushed a fix to master, so it will be available in the next release. I'll close this ticket once the change is live on Hex.

Thanks again!

**Comment by GriffinMB** [comment]
This is live in 0.9.3!
