### ISSUE TITLE
send_download not always captured

### ISSUE THREAD

**Issue by samhstn** [nccgroup/sobelow#55]
If we have a module which calls `Phoenix.Controller.send_download` as opposed to just `send_download`, it is not picked up.

The bug is captured by adding the following failing test in here: [`test/traversal/send_download_test.exs`](https://github.com/nccgroup/sobelow/blob/master/test/traversal/send_download_test.exs)

```elixir
test "vulnerable Phoenix.Controller.send_download" do
  func = """
  def index(conn, %{"test" => test}) do
    Phoenix.Controller.send_download(conn, {:file, test})
  end
  """

  {_, ast} = Code.string_to_quoted(func)

  assert SendDownload.parse_def(ast) |> is_vuln?
end
```

I haven't started investigating how to fix it yet

**Comment by GriffinMB** [comment]
I just pushed a change to master which should address the issue. You can test it out by installing from github: `mix archive.install github nccgroup/sobelow`

If you're interested, the problem stemmed from the fact that aliases needed to be checked specifically. You'd need to find functions with the function itself, eg `send_download` as well as functions with the alias `Controller.send_download`. This stemmed from an old architecture issue that is no longer relevant. The update should fix this problem and prevent it from occurring again!

I added your test case example, and I appreciate the help in flagging this issue! I'll leave this open until I make a new release to Hex, which will likely be this weekend.

Thanks again!

**Comment by samhstn** [comment]
Amazing, looks like it works as expected and thanks for the fast turn around @GriffinMB!

Looking forward to getting this released to Hex

**Comment by GriffinMB** [comment]
This is live in 0.9.3! Thanks again for the help :)
