### ISSUE TITLE
Possible to stop updating the timestamp in .sobelow file if --private flag is used?

### ISSUE THREAD

**Issue by benmap-brex** [nccgroup/sobelow#57]
Hey, first thanks for the hard work on this project!

I am trying to integrate sobelow into a git-based workflow, but one problem is the .sobelow file gets changed every time I run sobelow. This means that every time I run my unit tests + sobelow checks, git thinks I've modified .sobelow. It's confusing people who are unfamiliar with sobelow, and they ask why this mysterious file changes every time they run tests.

Is there any way you can update the code to prevent the timestamp changing in the .sobelow file if we use the `--private` flag?

**Comment by GriffinMB** [comment]
I’ll release an update to address this this week! Thanks for the suggestion :)

**Comment by benmap-brex** [comment]
Thanks for the quick response!

**Comment by GriffinMB** [comment]
Hi! The timestamp is now managed in a global "~/.sobelow/sobelow-vsn-check" file, similar to hex or similar libraries. This means that ".sobelow" will only be used for managing "skipped" findings, and it will only be created (or updated) when you run `mix sobelow --mark-all-skip`. 

Let me know how this works for you -- it's currently on master and can be installed with `mix archive.install github nccgroup/sobelow`. I will release to hex.pm once you've confirmed the update.

Thanks again for opening the issue :)

**Comment by benmap-brex** [comment]
Hey Griffin!

Looks good to me! Branch is nice and clean after running the tests :D

Thank you very much for the fix, you rock! I'd say release it, I haven't seen any issues after running tests.

**Comment by GriffinMB** [comment]
It's now live!

**Comment by benmap-brex** [comment]
If you're going to be at defcon / blackhat, let me buy you a beer!

**Comment by GriffinMB** [comment]
I doubt I'll be able to make it this year, but I'll hold you to it the year after :)
