### ISSUE TITLE
{:error, :eisdir} error after upgrade to 0.10.0

### ISSUE THREAD

**Issue by JMurphyWeb** [nccgroup/sobelow#58]
I have just upgraded my sobelow version from `0.9.3` -> `0.10.0`. 

On our CI (on Heroku) returns the following error:
```
-----> Running test command `MIX_ENV=test mix do format --check-formatted, sobelow --config, test && MIX_ENV=test mix ecto.rollback --all && (cd assets && npm audit --production)`...
Checking Sobelow version...
** (MatchError) no match of right hand side value: {:error, :eisdir}
    lib/sobelow.ex:479: Sobelow.load_ignored_fingerprints/1
    lib/sobelow.ex:128: Sobelow.init_state/2
    lib/sobelow.ex:74: Sobelow.run/0
    (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
    (elixir 1.10.0) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.0) lib/enum.ex:783: Enum.each/2
    (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.0) lib/mix/cli.ex:82: Mix.CLI.run_task/2
-----> test command `MIX_ENV=test mix do format --check-formatted, sobelow --config, test && MIX_ENV=test mix ecto.rollback --all && (cd assets && npm audit --production)` failed with exit status 1
```

Locally I can run:
`mix sobelow --config` no problem.

___
```
$ ls -a
.                               .iex.exs                        config                          mix.exs
..                              .sobelow-conf                   coveralls.json                  mix.lock
.elixir_ls                      Procfile                        deps                            phoenix_static_buildpack.config
.env                            README.md                       dump.rdb                        priv
.formatter.exs                  _build                          elixir_buildpack.config         release-task.sh
.git                            app.json                        infra                           test
.gitignore                      assets                          lib                             tmp
```
```
$ cat .sobelow-conf
[
  verbose: false,
  private: false,
  skip: true,
  router: "",
  exit: "Low",
  format: "txt",
  out: "",
  threshold: "low",
  ignore: ["Config.CSP", "XSS.Raw", "SQL.Query"],
  ignore_files: [""]
]
```

Is there an update guide? I couldn't see anything breaking-looking in the changelog 🤔 

Thanks in advance for any advice.

**Comment by GriffinMB** [comment]
There shouldn't be any breaking changes, so this is a bug on my side. I'll push an update to master today and confirm the fix with you.

Thanks for opening this issue!

**Comment by GriffinMB** [comment]
It looks like the project root is also the home directory in your CI, which is causing an issue with some file naming conventions. 

A new update has been pushed to master. You can download and test with `mix archive.install github nccgroup/sobelow`. Let me know if it solves your problem, and I will publish to Hex. 

Thanks again!

**Comment by JMurphyWeb** [comment]
Thanks for your help.

Trying: `{:sobelow, "~> 0.9.0", git: ["https://github.com/nccgroup/sobelow.git"], only: [:dev, :test]}`

**Comment by JMurphyWeb** [comment]
Looks good:
<img width="900" alt="Screenshot 2020-02-20 at 09 38 59" src="https://user-images.githubusercontent.com/12638261/74920922-d6c2af80-53c4-11ea-9698-bec63a9544fd.png">

🎉

**Comment by GriffinMB** [comment]
Excellent, thanks for testing it out. I'll push the updated release to Hex over the weekend. I'll leave this ticket open in the meantime.

**Comment by GriffinMB** [comment]
This is now live! Thanks again :)
