### ISSUE TITLE
Error: ranges (first..last) expect both sides to be integers...

### ISSUE THREAD

**Issue by romaluca** [nccgroup/sobelow#67]
When i launch 
`mix sobelow`
i receive this error:
`** (ArgumentError) ranges (first..last) expect both sides to be integers, got: 1..{:unquote, [line: 134], [{:+, [line: 134], [{:length, [line: 134], [{:path_args, [line: 134], nil}]}, 3]}]}
    (elixir 1.10.3) lib/range.ex:63: Range.new/2
    lib/sobelow/parse.ex:448: Sobelow.Parse.create_fun_cap/3
    lib/sobelow/parse.ex:427: Sobelow.Parse.get_funs_of_type/3
    (elixir 1.10.3) lib/macro.ex:410: Macro.do_traverse/4
    (elixir 1.10.3) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.10.3) lib/macro.ex:416: Macro.do_traverse/4
    (elixir 1.10.3) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.10.3) lib/macro.ex:396: Macro.do_traverse/4`

**Comment by GriffinMB** [comment]
Hi, thanks for opening this issue! I just pushed an update to Master that should solve the problem. You can test it out with `mix archive.install github nccgroup/sobelow`. Let me know if that works for you, and I will include it in the next release.

**Comment by romaluca** [comment]
Thanks, it works!
