### ISSUE TITLE
Cross-Site WebSocket Hijacking check false positive for Phoenix LiveView

### ISSUE THREAD

**Issue by jarrodldavis** [nccgroup/sobelow#72]
When generating a Phoenix app with LiveView, the endpoint has this line of code:

```elixir
socket "/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]]
```

Sobelow marks this as a potential for Cross-Site WebSocket Hijacking:

```
Config.CSWH: Cross-Site Websocket Hijacking - Low Confidence
File: lib/myapp_web/endpoint.ex
Line: 19


socket("/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]])
```

Curiously, this code for Phoenix Sockets (just above the `socket` declaration for LiveView) doesn't appear to be flagged at all:

```elixir
  socket "/socket", StringBookWeb.UserSocket,
    websocket: true,
    longpoll: false
```

It appears the `Config.CSWH` only reports potential issues when the `websocket` configuration is a keyword list, and even ignores `check_origin: true` when explicitly set in that keyword list rather than [implicitly from the endpoint configuration][endpoint-socket] (such as from `config/config.exs` or `config/dev.exs`):

https://github.com/nccgroup/sobelow/blob/8634de7994a8ca175ea14b8d7be2ff884a677c60/lib/sobelow/config/cswh.ex#L37-L47

I know that Sobelow errs on the side of over-reporting (which is ultimately a good thing), but since [only function declarations can be skipped][false-positives] (which isn't readily available in the endpoint file), it would be nice if the check at least took an explicit `check_origin: true` configuration into account. It would also be nice if the [global endpoint configuration][endpoint-socket] were taken into account, but I understand that's probably unreasonable since it would need to correlate state across multiple files.

[false-positives]: https://github.com/nccgroup/sobelow#false-positives
[endpoint-socket]: https://hexdocs.pm/phoenix/1.5.3/Phoenix.Endpoint.html#socket/3-common-configuration

**Comment by GriffinMB** [comment]
Thanks for opening this issue! While you're waiting on a fix, you can use the --mark-skip-all flag to mark it as a false positive. You can find usage details here: https://sobelow.io/#v090

**Comment by GriffinMB** [comment]
I added checks for the `nil` and `true` socket options cases, so this should no longer be incorrectly flagging LiveView's default socket configuration. The change is on master, so you can install and test with `mix archive.install github nccgroup/sobelow`.

Let me know if that works for you, and I will publish to Hex.

Thanks again!

**Comment by jarrodldavis** [comment]
@GriffinMB I've tested the updated check and it works great!

**Comment by GriffinMB** [comment]
Meant to close this, sorry for the delay. This is in the latest release! Thanks again.
