### ISSUE TITLE
Enable SARIF Report Output

### ISSUE THREAD

**Issue by josepalafox** [nccgroup/sobelow#77]
Add SARIF as a supported output format.

SARIF is an oasis standard JSON format that aims to standardize the format of security alerts so that the data is normalized and can be integrated into a number of other tools.

GitHub supports the SARIF format and enables developers of open source projects and public repositories to view security alerts directly in the GitHub UI.

https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github

**Comment by GriffinMB** [comment]
I need to clean up the help text a bit and improve the sarif tests, but this is now working as expected: https://github.com/GriffinMB/phx_demo/security/code-scanning/4?query=ref%3Arefs%2Fheads%2Fmaster

**Comment by GriffinMB** [comment]
This is done. Commit here: https://github.com/nccgroup/sobelow/commit/51aa8aaa38eda9b646e20d1178b0344c05e5a79b
