### ISSUE TITLE
Create CI Integration

### ISSUE THREAD

**Issue by josepalafox** [nccgroup/sobelow#78]
As part of integrating security into the app dev lifecycle users are interested in initiating code scans using GitHub Actions.

A hosted GitHub Action would enable developers of open source software and public repos on GitHub.com to scan code on a PR. https://docs.github.com/en/free-pro-team@latest/actions

An additional action added to a workflow https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#workflows to upload a SARIF formatted report will surface the alerts in the Github.com as described in #77

**Comment by GriffinMB** [comment]
Action is created: https://github.com/sobelow/action

I'll publish v1 and update docs this week, and that should wrap up the Action/CI issues!

**Comment by GriffinMB** [comment]
Hosted action here: https://github.com/marketplace/actions/sobelow
