### ISSUE TITLE
Swap order of the compact report entries

### ISSUE THREAD

**Issue by hauleth** [nccgroup/sobelow#80]
Currently the format is:

```
{report} - {file}:{line}
```

Which makes it hard to automatically parse (for example using Vim's `errorformat`. It would be much easier to have such format printed as:

```
{file}:{line} - {report}
```

Which would make that much simpler. It would also add support for tools like Reviewdog for having reports in other tools, that currently do not support SARIF format (additionally SARIF format do not support streaming, which can be troublesome sometimes).

**Comment by GriffinMB** [comment]
I'll add a new flag that reverses the compact output. Let me know if you have any thoughts on naming, otherwise I'll go with something like "rcompact"

**Comment by hauleth** [comment]
Or make it `{file}:{line}: {report}` and call it `flycheck`. This is the naming the Credo uses.

**Comment by GriffinMB** [comment]
I added a flycheck format (and `--flycheck` flag) that reverses the compact output. You can install with `mix escript.install github nccgroup/sobelow` and test it out.

**Comment by GriffinMB** [comment]
This is in the latest release! Thanks again
