### ISSUE TITLE
Formatting as json with `-f json` causes crash.

### ISSUE THREAD

**Issue by alex0112** [nccgroup/sobelow#89]
### Description:

Running sobelow with the option to output a JSON report (`mix sobelow -f json`) produces an exception.

### Steps to reproduce:
- Fresh install of sobelow with `$ mix archive.install hex sobelow` per README instructions
- run `$ mix sobelow -f json` in a project containing a mix.exs file
```bash
$  mix sobelow -f json
** (UndefinedFunctionError) function Jason.encode!/2 is undefined (module Jason is not available)
    Jason.encode!(%{findings: %{high_confidence: [], low_confidence: [%{file: "lib/project/foo_bar.ex", line: 42, type: "SomeError", variable: :user_action_type}, %{file: "lib/project/foo_bar.ex", line: 42, type: "AnotherError", variable: :sql}], medium_confidence: []}, sobelow_version: "0.11.1", total_findings: 2}, [pretty: true])
    lib/sobelow.ex:142: Sobelow.print_output/0
    lib/sobelow.ex:120: Sobelow.run/0
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2

```

### Environment Information:
- Sobelow Version: `v0.11.1` (Tried with both published hex package, and build from master branch on github)
- Operating System: MacOS Catalina 10.15.7, error also occurs on a Debian based docker image.

### Notes:
Digging in to the stack trace a little indicates that [`Sobelow.print_output/0`](https://github.com/nccgroup/sobelow/blob/master/lib/sobelow.ex#L142) makes a call to `Sobelow.FindingLog.json/1` which attempts to call [`Jason.encode!/1`](https://github.com/nccgroup/sobelow/blob/master/lib/sobelow/finding_log.ex#L22) but is unable to find `Jason` within the scope of the current module. When building the module or running the install command provided by the README, `Jason` is being installed as a dependency. However, `Jason` is not being `alias`ed into the `FindingLog` module definition, which may be causing the issue.

**Comment by GriffinMB** [comment]
Hey! Thanks for opening this issue. It looks like I missed a README update - as of 11.0, you should install Sobelow with `mix escript.install hex sobelow`. The [Changelog](https://sobelow.io/#v0110) has some additional details. Let me know if that fixes your issue, and I will update the README now.

**Comment by alex0112** [comment]
Installing with `mix escript.install` got it running again. Thank you!
